version: 2

models:
  - name: stg_tokyo_crimes
    columns:
      - name: tokyo_crimes_id
        tests:
          - not_null
          - unique
      - name: teguchi
        tests:
          - not_null
          - accepted_values:
              values:
                [
                  "ひったくり",
                  "オートバイ盗",
                  "自動車盗",
                  "部品ねらい",
                  "自動販売機ねらい",
                  "車上ねらい",
                  "自転車盗",
                ]
      - name: occurrence_date
        tests:
          - not_null
  - name: stg_daily_weathers
    columns:
      - name: weather_date
        tests:
          - not_null
          - unique
